import type { Config } from "tailwindcss"

const config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  safelist: [
    // Background gradients
    'bg-gradient-to-r',
    'bg-gradient-to-br',
    'from-slate-50',
    'via-blue-50',
    'to-green-50',
    'from-lime-50',
    'to-green-50',
    'from-orange-50',
    'to-red-50',
    'from-blue-50',
    'to-indigo-50',
    'from-lime-400',
    'to-green-500',
    'from-orange-400',
    'to-red-500',
    'from-blue-400',
    'to-indigo-500',
    'from-slate-100',
    'to-slate-50',
    'from-green-50',
    'to-emerald-50',
    'from-slate-800',
    'to-slate-600',
    // Background colors
    'bg-white/80',
    'bg-gradient-to-br',
    'bg-lime-200',
    'bg-orange-200',
    'bg-blue-200',
    'bg-green-100',
    'bg-green-500',
    'bg-green-200',
    'bg-coral-100',
    'bg-coral-200',
    'bg-slate-100',
    'bg-slate-300',
    'bg-slate-50',
    // Text colors
    'text-lime-500',
    'text-lime-600',
    'text-orange-500',
    'text-blue-500',
    'text-green-500',
    'text-green-600',
    'text-green-700',
    'text-green-800',
    'text-coral-600',
    'text-coral-700',
    'text-slate-500',
    'text-slate-600',
    'text-slate-700',
    'text-slate-800',
    // Border colors
    'border-white/20',
    'border-lime-200/50',
    'border-orange-200/50',
    'border-blue-200/50',
    'border-green-200',
    'border-green-200/50',
    'border-slate-200',
    'border-slate-200/50',
    'border-coral-300',
    // Effects
    'backdrop-blur-sm',
    'shadow-lg',
    'shadow-sm',
    'shadow-green-200',
    // Hover states
    'hover:bg-slate-50',
    'hover:bg-coral-200',
    'hover:bg-green-100',
    'hover:text-green-700',
    'hover:border-coral-300',
    'hover:border-green-300',
    'hover:shadow-md',
    'hover:scale-[1.01]',
    'hover:from-lime-500',
    'hover:to-green-600',
    'hover:from-orange-500',
    'hover:to-red-600',
    'hover:from-green-500',
    'hover:to-emerald-600',
    'hover:bg-coral-400',
    'hover:bg-green-400',
    // Group hover
    'group-hover:bg-coral-400',
    'group-hover:bg-green-400',
    'group-hover:bg-coral-200',
    'group-hover:bg-green-100',
    'group-hover:text-green-700',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        coral: {
          50: "#fff7ed",
          100: "#ffedd5",
          200: "#fed7aa",
          300: "#fdba74",
          400: "#fb923c",
          500: "#f97316",
          600: "#ea580c",
          700: "#c2410c",
          800: "#9a3412",
          900: "#7c2d12",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} as const

export default config
